name       : arandr
version    : 0.1.9
release    : 1
source     :
    - http://christian.amsuess.com/tools/arandr/files/arandr-0.1.9.tar.gz : bb2b57dc37787c4eb7c33c5136cea3829d1b885862cdd827f16ef51e9f0a6ec4
license    : GPL-3.0
component  : desktop
summary    : A simple visual front end for XRandR
description: |
    ARandR is designed to provide a simple visual front end for XRandR.
    Relative monitor positions are shown graphically and can be changed
    in a drag-and-drop way.
builddeps  :
    - python-docutils
rundeps    :
    - python-gobject2
    - xrandr
build      : |
    %python_setup
install    : |
    %python_install
