name       : arandr
version    : 0.1.10
release    : 7
source     :
    - http://christian.amsuess.com/tools/arandr/files/arandr-0.1.10.tar.gz : dbc8ac890da78e9c0ba3403a8932a925813bb8d62265276894e780ba2905b88c
homepage   : http://christian.amsuess.com/tools/arandr/
license    : GPL-3.0-or-later
component  : desktop
summary    : A simple visual front end for XRandR
description: |
    ARandR is designed to provide a simple visual front end for XRandR. Relative monitor positions are shown graphically and can be changed in a drag-and-drop way.
builddeps  :
    - python-docutils
rundeps    :
    - python-gobject
    - python3-cairo
    - xrandr
build      : |
    %python3_setup
install    : |
    %python3_install
